# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyValueStore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keyValueStore.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13keyValueStore.proto\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x02(\x05\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x02(\t\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x02(\x05\x12\r\n\x05value\x18\x02 \x02(\t\"\x1c\n\x0c\x46lagResponse\x12\x0c\n\x04\x66lag\x18\x01 \x02(\x05\"(\n\x11ServiceActivation\x12\x13\n\x0bserviceName\x18\x01 \x02(\t\"\x0c\n\nStopParams2\xa1\x01\n\rKeyValueStore\x12&\n\x06Insert\x12\r.KeyValuePair\x1a\r.FlagResponse\x12\x15\n\x05Query\x12\x04.Key\x1a\x06.Value\x12-\n\x08\x41\x63tivate\x12\x12.ServiceActivation\x1a\r.FlagResponse\x12\"\n\x04Stop\x12\x0b.StopParams\x1a\r.FlagResponse')
)




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Key.key', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=41,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Value.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=65,
)


_KEYVALUEPAIR = _descriptor.Descriptor(
  name='KeyValuePair',
  full_name='KeyValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyValuePair.key', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='KeyValuePair.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=109,
)


_FLAGRESPONSE = _descriptor.Descriptor(
  name='FlagResponse',
  full_name='FlagResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='FlagResponse.flag', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=139,
)


_SERVICEACTIVATION = _descriptor.Descriptor(
  name='ServiceActivation',
  full_name='ServiceActivation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serviceName', full_name='ServiceActivation.serviceName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=181,
)


_STOPPARAMS = _descriptor.Descriptor(
  name='StopParams',
  full_name='StopParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['KeyValuePair'] = _KEYVALUEPAIR
DESCRIPTOR.message_types_by_name['FlagResponse'] = _FLAGRESPONSE
DESCRIPTOR.message_types_by_name['ServiceActivation'] = _SERVICEACTIVATION
DESCRIPTOR.message_types_by_name['StopParams'] = _STOPPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
  DESCRIPTOR = _KEY,
  __module__ = 'keyValueStore_pb2'
  # @@protoc_insertion_point(class_scope:Key)
  ))
_sym_db.RegisterMessage(Key)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'keyValueStore_pb2'
  # @@protoc_insertion_point(class_scope:Value)
  ))
_sym_db.RegisterMessage(Value)

KeyValuePair = _reflection.GeneratedProtocolMessageType('KeyValuePair', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUEPAIR,
  __module__ = 'keyValueStore_pb2'
  # @@protoc_insertion_point(class_scope:KeyValuePair)
  ))
_sym_db.RegisterMessage(KeyValuePair)

FlagResponse = _reflection.GeneratedProtocolMessageType('FlagResponse', (_message.Message,), dict(
  DESCRIPTOR = _FLAGRESPONSE,
  __module__ = 'keyValueStore_pb2'
  # @@protoc_insertion_point(class_scope:FlagResponse)
  ))
_sym_db.RegisterMessage(FlagResponse)

ServiceActivation = _reflection.GeneratedProtocolMessageType('ServiceActivation', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEACTIVATION,
  __module__ = 'keyValueStore_pb2'
  # @@protoc_insertion_point(class_scope:ServiceActivation)
  ))
_sym_db.RegisterMessage(ServiceActivation)

StopParams = _reflection.GeneratedProtocolMessageType('StopParams', (_message.Message,), dict(
  DESCRIPTOR = _STOPPARAMS,
  __module__ = 'keyValueStore_pb2'
  # @@protoc_insertion_point(class_scope:StopParams)
  ))
_sym_db.RegisterMessage(StopParams)



_KEYVALUESTORE = _descriptor.ServiceDescriptor(
  name='KeyValueStore',
  full_name='KeyValueStore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=198,
  serialized_end=359,
  methods=[
  _descriptor.MethodDescriptor(
    name='Insert',
    full_name='KeyValueStore.Insert',
    index=0,
    containing_service=None,
    input_type=_KEYVALUEPAIR,
    output_type=_FLAGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='KeyValueStore.Query',
    index=1,
    containing_service=None,
    input_type=_KEY,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Activate',
    full_name='KeyValueStore.Activate',
    index=2,
    containing_service=None,
    input_type=_SERVICEACTIVATION,
    output_type=_FLAGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='KeyValueStore.Stop',
    index=3,
    containing_service=None,
    input_type=_STOPPARAMS,
    output_type=_FLAGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYVALUESTORE)

DESCRIPTOR.services_by_name['KeyValueStore'] = _KEYVALUESTORE

# @@protoc_insertion_point(module_scope)
