# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import keyValueStore_pb2 as keyValueStore__pb2


class KeyValueStoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Insert = channel.unary_unary(
        '/KeyValueStore/Insert',
        request_serializer=keyValueStore__pb2.KeyValuePair.SerializeToString,
        response_deserializer=keyValueStore__pb2.FlagResponse.FromString,
        )
    self.Query = channel.unary_unary(
        '/KeyValueStore/Query',
        request_serializer=keyValueStore__pb2.Key.SerializeToString,
        response_deserializer=keyValueStore__pb2.Value.FromString,
        )
    self.Activate = channel.unary_unary(
        '/KeyValueStore/Activate',
        request_serializer=keyValueStore__pb2.ServerAddr.SerializeToString,
        response_deserializer=keyValueStore__pb2.FlagResponse.FromString,
        )
    self.Stop = channel.unary_unary(
        '/KeyValueStore/Stop',
        request_serializer=keyValueStore__pb2.StopParams.SerializeToString,
        response_deserializer=keyValueStore__pb2.FlagResponse.FromString,
        )


class KeyValueStoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Insert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Activate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Insert': grpc.unary_unary_rpc_method_handler(
          servicer.Insert,
          request_deserializer=keyValueStore__pb2.KeyValuePair.FromString,
          response_serializer=keyValueStore__pb2.FlagResponse.SerializeToString,
      ),
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=keyValueStore__pb2.Key.FromString,
          response_serializer=keyValueStore__pb2.Value.SerializeToString,
      ),
      'Activate': grpc.unary_unary_rpc_method_handler(
          servicer.Activate,
          request_deserializer=keyValueStore__pb2.ServerAddr.FromString,
          response_serializer=keyValueStore__pb2.FlagResponse.SerializeToString,
      ),
      'Stop': grpc.unary_unary_rpc_method_handler(
          servicer.Stop,
          request_deserializer=keyValueStore__pb2.StopParams.FromString,
          response_serializer=keyValueStore__pb2.FlagResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'KeyValueStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CentralServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/CentralServer/Register',
        request_serializer=keyValueStore__pb2.PairServer.SerializeToString,
        response_deserializer=keyValueStore__pb2.PairCount.FromString,
        )
    self.MapToServer = channel.unary_unary(
        '/CentralServer/MapToServer',
        request_serializer=keyValueStore__pb2.Key.SerializeToString,
        response_deserializer=keyValueStore__pb2.ServerAddr.FromString,
        )
    self.StopCentralServer = channel.unary_unary(
        '/CentralServer/StopCentralServer',
        request_serializer=keyValueStore__pb2.StopParams.SerializeToString,
        response_deserializer=keyValueStore__pb2.PairCount.FromString,
        )


class CentralServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MapToServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopCentralServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CentralServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=keyValueStore__pb2.PairServer.FromString,
          response_serializer=keyValueStore__pb2.PairCount.SerializeToString,
      ),
      'MapToServer': grpc.unary_unary_rpc_method_handler(
          servicer.MapToServer,
          request_deserializer=keyValueStore__pb2.Key.FromString,
          response_serializer=keyValueStore__pb2.ServerAddr.SerializeToString,
      ),
      'StopCentralServer': grpc.unary_unary_rpc_method_handler(
          servicer.StopCentralServer,
          request_deserializer=keyValueStore__pb2.StopParams.FromString,
          response_serializer=keyValueStore__pb2.PairCount.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CentralServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
